copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Items.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Units.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Heroes.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Players.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Clans.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Races.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Quests.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Researches.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Bosses.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Spells.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Buildings.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Professions.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
copy "C:\Users\Tamino\Documents\Warcraft III\CustomMapData\WorldOfWarcraftReforged-Mounts.txt" "C:\Users\Tamino\Documents\Projekte\wowr-website\map"
pause
